version: "3.8"

services:
    redis:
        image: redis
        command: redis-server
        ports:
            - "6379:6379"
        hostname: redis
        volumes:
            - ./data:/data
        networks:
          - redis-net
        restart: always 

    app:
        image: golang
        command: go run main.go -f config.json
        depends_on:
          - redis
        ports:
            - "80:80"
        volumes:
          - .:/go/src
        working_dir: /go/src
        networks:
          - redis-net
        restart: always 
        
networks:
  redis-net: